name: Github Action to Tag and Push images of changed Packages
run-name: Create images for updated packages to deploy on production

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REGISTRY: ghcr.io
on:
  push:
    tags: ['*.*.*']

jobs:
  retag-to-latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ['frontend', 'backend']
    permissions:
      contents: read
      packages: write
    steps:
      - name: Print Tag
        run: | 
          echo "Running build step for tag: ${{ github.ref_name }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Docker log into ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ env.GITHUB_TOKEN }}
      - name: Pull and retag as latest
        env:
            image: ${{ env.REGISTRY }}/j-toscani/vokabelfest-${{ matrix.project }}:staging
        run: |
          docker pull ${{ env.image }}
          docker tag ${{ env.image }} vokabelfest-${{ matrix.project }}:${{ github.ref_name }}
          docker tag ${{ env.image }} vokabelfest-${{ matrix.project }}:latest
          docker push --all-tags ${{ env.image }}